//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_ticaret_MVC_projesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uyeler()
        {
            this.favoriler = new HashSet<favoriler>();
            this.siparisler = new HashSet<siparisler>();
        }
    
        public int uyeid { get; set; }
        public string kuladi { get; set; }
        public string sifre { get; set; }
        public string adsoyad { get; set; }
        public System.DateTime dogtar { get; set; }
        public bool cinsiyet { get; set; }
        public string adres { get; set; }
        public byte plaka { get; set; }
        public string email { get; set; }
        public short meslekid { get; set; }
        public Nullable<bool> onay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favoriler> favoriler { get; set; }
        public virtual meslek meslek { get; set; }
        public virtual sehirler sehirler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siparisler> siparisler { get; set; }
    }
}
